### ISSUE TITLE
Where is the file data_centers.csv?

### ISSUE THREAD

**Issue by ghost** [jhacsonmeza/MarkerPose#2]
Thanks

**Comment by jhacsonmeza** [comment]
This .csv file has the image filenames and points to train SuperPoint. Here's an example.

<html>
<body>


FileName | c0x | c0y | cXx | cXy | cYx | cYy
-- | -- | -- | -- | -- | -- | --
im0.png | 235.370333241151 | 140.729688796322 | 263.602094925572 | 144.222060475817 | 257.390787370105 | 90.440059883911
im1.png | 219.555501233878 | 135.091613266518 | 247.565308553729 | 132.685031719085 | 229.869462232708 | 82.305297508707
im2.png | 216.047839314541 | 125.647720569974 | 243.183653388694 | 123.773588539639 | 224.517527087317 | 65.8785203553218

</body>
</html>

Unfortunately the images aren't available. I don't know if you just need the .csv file.

**Comment by songs-for-you** [comment]
Hello,I am also having trouble finding the data_centers.csv file. And how can I use the data above to run train_superpoint.py?
Also, when I run the train_ellipsegnet.py , it gives me a ValueError: num_samples should be a positive integer value, but got num_samples=0. How can I fix this?

**Comment by jhacsonmeza** [comment]
Hi @songs-for-you as I mentioned before, unfortunately the dataset for training the SuperPoint network isn't available.

You can find here https://github.com/jhacsonmeza/MarkerPose/issues/1#issuecomment-872415774 the dataset and an instruction to run `train_ellipsegnet.py`. I suppose your error is because you don't have the dataset.

**Comment by songs-for-you** [comment]
> Hi @songs-for-you as I mentioned before, unfortunately the dataset for training the SuperPoint network isn't available.
> 
> You can find here [#1 (comment)](https://github.com/jhacsonmeza/MarkerPose/issues/1#issuecomment-872415774) the dataset and an instruction to run `train_ellipsegnet.py`. I suppose your error is because you don't have the dataset.

Thank u!

**Comment by songs-for-you** [comment]
hello,sorry to ask one more question.
After doing what you said in #1(comment) , i still can't get the correct output. When running train_superpoint.py, it throws an error:ValueError: AttributeError: 'NoneType' object has no attribute 'shape'
And when running train_ellipsegnet.py, it throws ValueError: num_samples should be a positive integer value, but got num_samples=0. How can I manage to solve this?

**Comment by jhacsonmeza** [comment]
Hi @songs-for-you 

I think you're a bit confused with `train_ellipsegnet.py` and `train_superpoint.py`. The previous instructions where for training EllipSegNet with `train_ellipsegnet.py`, and your're talking about training SuperPoint using `train_superpoint.py` and I said that this dataset is not available. The error you're obtaining is because you don't have the dataset for using `train_superpoint.py` and this dataset is not available. In other words, if you want to use `train_superpoint.py` you need to use your own dataset.

**Comment by songs-for-you** [comment]
> Hi @songs-for-you
> 
> I think you're a bit confused with `train_ellipsegnet.py` and `train_superpoint.py`. The previous instructions where for training EllipSegNet with `train_ellipsegnet.py`, and your're talking about training SuperPoint using `train_superpoint.py` and I said that this dataset is not available. The error you're obtaining is because you don't have the dataset for using `train_superpoint.py` and this dataset is not available. In other words, if you want to use `train_superpoint.py` you need to use your own dataset.

Thanks

**Comment by arsalanshakeel** [comment]
Hello @jhacsonmeza, Thank you for the code. I have a simple question because I am stuck at a point. 
Is the above-mentioned sample data_centers.csv file was created: 
1. After resizing the images to (320,240) and then annotating the points in a .csv file. ("This is my understanding, please correct me if I am wrong.")
2. Or the images were annotated at full resolution in a .csv file and later images were resized in the data augmentation.
 
I would appreciate your help. Thank you

**Comment by jhacsonmeza** [comment]
Hi,
Thank you for asking. I tried both of the options you mentioned. Except for a slight change in **1.** where the keypoints were estimated in full resolution and then both the images and the keypoints were resized to 320x240. And with these resized points we generated the CSV file. Keypoints weren't estimated in a resize version of the images. 

We also tried exactly what you mentioned in **2.**. However, thinking in terms of runtime, the first option is faster. The problem with the second idea is that if you're going to resize the images on-the-fly for every iteration, we're going to spend more time loading a full resolution image and then resizing. That's why we preferred **1.** and you can see [here](https://github.com/jhacsonmeza/MarkerPose/blob/91b4761e7332e56381f0236dd51bd6adfeede329/Python/modules/dataset.py#L24-L25) that we just read the images, we don't resize anything. Inside [`transformer_superpoint`](https://github.com/jhacsonmeza/MarkerPose/blob/91b4761e7332e56381f0236dd51bd6adfeede329/Python/modules/transformations.py#L108) we also don't apply resizing.

Hope this can help.

**Comment by arsalanshakeel** [comment]
@jhacsonmeza 

Thank you for the last comment that was very helpful. However, I have one more thing to ask, As you can see in the below figure, inside the SortedPoint function, in order to return the indices for the non-zero scores using torch.nonzero, a value that is 0.015 is set as the threshold for scores.

The thing that I want to ask is, whether the value was pre-calculated or was it entirely assumed.
I would appreciate your help. Thank You. 
![sorted_points](https://user-images.githubusercontent.com/77706553/210462470-02172538-cf99-4c96-9b9e-b67f7215368e.JPG)

**Comment by jhacsonmeza** [comment]
That's a value used in multiple SuperPoint implementations. For example, in the [official repo](https://github.com/magicleap/SuperPointPretrainedNetwork) you can see that that value is set [here](https://github.com/magicleap/SuperPointPretrainedNetwork/blob/master/demo_superpoint.py#L603). In other unofficial SuperPoint implementations, that same 0.015 threshold is used [here](https://github.com/rpautrat/SuperPoint/blob/6d830927e89308d353b5b368a76acb3405d5bada/superpoint/configs/magic-point_coco_export.yaml#L9), and also 0.01 is set [here](https://github.com/rpautrat/SuperPoint/blob/6d830927e89308d353b5b368a76acb3405d5bada/superpoint/configs/superpoint_coco.yaml#L46). To be honest, I didn't try changing that threshold value but I suppose it was established empirically.

**Comment by arsalanshakeel** [comment]
@jhacsonmeza Thanks for the comment, unfortunately, I made an error by changing the threshold value in the simple_nms function which resulted in a lesser number of points, however, I have fixed the issue, and now it's working accurately.

**Comment by jhacsonmeza** [comment]
Glad it worked for you! Let me know when you have another question.

**Comment by ChasePlan** [comment]
Hello, I would like to know how you obtained the true centers of three ellipses for the SuperPoint network training dataset?How did you measure the true point coordinates in the CSV file?Thank you very much for taking the time to answer my question!

**Comment by jhacsonmeza** [comment]
Hi @ChasePlan. This is an example of how we obtained the ground truth centers: [ground_truth.txt](https://github.com/jhacsonmeza/MarkerPose/files/14564370/ground_truth.txt)
I couldn't upload the file as `.py`, so change the extension to `.py` and run it. You can try the code with this image: [example.png](https://github.com/jhacsonmeza/MarkerPose/assets/29784391/05e60e0c-5f01-4800-a9f5-2ad672e65b7a)
Note that this isn't robust for different cases. Sometimes you'll need to adapt some parameters to make it work. That's the main motivation why we proposed the center detection with DL.
