### ISSUE TITLE
Training for randomly placed markers?

### ISSUE THREAD

**Issue by antithing** [jhacsonmeza/MarkerPose#3]
Hi, and thank you for making this code available, I have it running perfectly on your dataset.

I would like to adapt it for use as a general marker detector, to be used to find the centre points of randomly placed markers in a space. Something like this:

![temp](https://user-images.githubusercontent.com/11506730/131651715-a613394e-b060-4457-8fb4-e5be3d9d0a3b.jpg)

Where markers could be on any plane, and there could be any number of them. The camera is moving, so markers would come in and out of frame and the number of markers in frame would change dynamically.  I would not need the classification step, just the sub pixel point detection.

Do you have any tips for training the models for this use? I imagine the ellipsegnet can stay the same as it is, but i would need to re-train the superpoint network on different images, is that right?

Thanks again!

**Comment by jhacsonmeza** [comment]
Thank you! I'm glad you were able to use the code perfectly.

About your question, you are right, the stage with EllipSegNet doesn't need any change. On the other hand, the keypoint detection head from the SuperPoint network generates a heatmap with a maximum response on the circles' location. Based on that, I think you can try using it (without retraining) no matter how many circles are in the image. You just need to ignore the classification head output or get rid of it in the model. However, if you have a custom dataset, you can use the same [`train_superpoint.py`](https://github.com/jhacsonmeza/MarkerPose/blob/main/Python/train_superpoint.py) file we used for training. You just need to do some modifications, for example, in the data generator, metrics, and the network to remove the classification part.

I hope this can help in some way.
Sorry for the delayed response and thank you for your question!

**Comment by Oguked** [comment]
I want to enhance your model to generalize to more markers with arbritrary locations, but a few things are still unclear to me. 
Why does the feature map from the point localization head of the SuperPoint-like network have 65 channels (W/8 x H/8 x 65)? This feature map indicates possible locations of the markers, right? Wouldn't one channel be enough (W/8 x H/8 x 1)? How can I interpret the 65 channels?

**Comment by jhacsonmeza** [comment]
Hi @Oguked 

If you have an image of size WxH, you have to split it into non-overlapping 8x8 patches (for that you need W and H to be multiples of 8). 

![patches_](https://user-images.githubusercontent.com/29784391/145172155-2e6a4c37-7a0e-498f-b331-db3aba3a7514.png)

Then, inside each 8x8 region you flatten the values in the channels dimension, so you obtain 8x8 = 64 channels and W/8 columns and H/8 rows. In other words, your image becomes W/8 x H/8 x 64.

![tensor_](https://user-images.githubusercontent.com/29784391/145172274-7fb677ec-786e-4521-bb55-e1e1918537a1.png)

However, for the classification problem we add an additional channel which represent non-keypoint pixels. The idea is that each channel is a bin for the probability to find a keypoint in a specific 8x8 region. Then, the additional channel is for cases where in a given 8x8 region there's no keypoint. It's like the background class in segmentation tasks that is used to represent non-objects. That's why we end up with a tensor with shape W/8 x H/8 x 65 instead of W/8 x H/8 x 64.

Hope this can help.
